### PR TITLE
Bicep updates for validation and clean up

### PR DESCRIPTION
**Pull request by BernieWhite**
# Change

- Updates to bicep files and straggling parameter files.
- Added tweaks to parameter validation and docs.
- Added example for PSRule integration as WAF aligned tests.

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (readme)
- [x] I did format my code

### CODE REVIEW

**Comment by MrMCake** [comment]
Will be introduced once the work surrounding #1624 is completed

**Comment by BernieWhite** [comment]
@MrMCake Is this something that we can reactivate now #1624 is done, or are we waiting for #1787 as well?

**Comment by AlexanderSehr** [comment]
Hey @BernieWhite please excuse the very late reply - have always had your PR in the back of my head as we get closer to enabling its implementation (finally). So we are we at now:
- The one major 'issue' we're currently wrapping up (ETA end of this month, ideally sooner) is #1791 which will unblock PSRule for us (finally). Everthing until now was pretty much enabling the Bicep-Test files, #1791 is implementing them
- @eriqua was so keen to start working on PSRule and testing it with several of our already prepared modules. To roll it out on scale, we have several issues like #2149, #2150, #2151 & #2026. 
As far as I'm concerned, this will be our next big focus area once #1791 is merged - and any guidance you can provide is naturally more than welcome. If I understood @eriqua correctly, it will be some work to both finetune the rules for CARML (as some rules, for example, apply better to solutions rather than modules) and also address any findings. :)

**Comment by eriqua** [comment]
@BernieWhite PSRule has finally been integrated with GitHub workflows. Ref:
- #2425 
- #2426 

Currently this is implemented in audit mode. Meanwhile, we're working on module tests to adhere with the rules. Ref:
- #2151

This was very much thanks to this draft PR, which helped us getting the base of the implementation. 

@BernieWhite @AlexanderSehr if you agree I would then suggest to close this PR.

**Pull request closed without merging**
