### PR TITLE
update PIP

### PR DESCRIPTION
**Pull request by rahalan**
# Change

Adding some additional parameters and adding allowed values to existing ones

successful run: [Network: PublicIpAddresses](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.publicipaddresses.yml)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (Wiki)

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (readme)
- [x] I did format my code

### CODE REVIEW

**Review by eriqua — COMMENTED** [review]
Looks good! I'm wondering:
- Should we consistently update also nested pip modules across the repo (e.g. the one in the vm)? 
- Should we extend the parameter file(s) with new values?

**Comment by rahalan** [comment]
We have a discussion today about module dependencies. The outcome may be, that we will reference just this one PIP module.

**Comment by segraef** [comment]
> Looks good! I'm wondering:
> 
> * Should we consistently update also nested pip modules across the repo (e.g. the one in the vm)?
> * Should we extend the parameter file(s) with new values?

Makes sense but implies low priority effort. It also screams for a nested module dependency list then.
Regarding the parameters, optional is optional.

**Comment by segraef** [comment]
> 

Even better, which would also eliminate my previous comment about the dependencies then, Thanks.

**Comment by segraef** [comment]
> We have a discussion today about module dependencies. The outcome may be, that we will reference just this one PIP module.

Even better, which would also eliminate my previous comment about the dependencies then, Thanks.

**Review by eriqua — APPROVED** [review]
🆗

**Pull request merged**
