### PR TITLE
[Modules] Fix API version issues

### PR DESCRIPTION
**Pull request by MariusStorhaug**
# Description

All pipelines be breaking on my end, so thought I would just bump a version and regen all files.

- API version bump of modules:
  - applicationGateways (2022-07-01) -> (2023-05-01)
  - applicationSecurityGroups (2022-07-01) -> (2023-05-01)
  - azureFirewalls (2022-07-01) -> (2023-05-01)
  - connections (2022-07-01) -> (2023-05-01)
  - ddosProtectionPlans (2022-07-01) -> (2023-05-01)
  - expressRouteCircuits (2022-07-01) -> (2023-05-01)
  - firewallPolicies (2022-07-01) -> (2023-05-01)
  - ipGroups (2022-07-01) -> (2023-05-01)
  - loadBalancers (2022-07-01) -> (2023-05-01)
  - localNetworkGateways (2022-07-01) -> (2023-05-01)
  - natGateways (2022-07-01) -> (2023-05-01)
  - networkInterfaces (2022-07-01) -> (2023-05-01)
  - networkSecurityGroups (2022-07-01) -> (2023-05-01)
  - networkWatchers (2022-07-01) -> (2023-05-01)
  - networkWatchers/connectionMonitors (2022-07-01) -> (2023-05-01)
  - networkWatchers/connectionMonitors (2022-07-01) -> (2023-05-01)
  - networkWatchers/flowLogs (2022-07-01) -> (2023-05-01)
  - networkWatchers/flowLogs (2022-07-01) -> (2023-05-01)
  - privateEndpoints (2022-07-01) -> (2023-05-01)
  - privateEndpoints/privateDnsZoneGroups (2022-07-01) -> (2023-04-01)
  - publicIPAddresses (2022-07-01) -> (2023-05-01)
  - publicIPPrefixes (2022-07-01) -> (2023-05-01)
  - routeTables (2022-07-01) -> (2023-05-01)
  - serviceEndpointPolicies (2022-07-01) -> (2023-05-01)
  - virtualNetworkGateways  (2022-07-01) -> (2023-05-01)
  - virtualNetworks (2022-07-01) -> (2023-05-01)
  - virtualWans (2022-07-01) -> (2023-05-01)
  - vpnGateways (2022-07-01) -> (2023-05-01)
  - vpnSites (2022-07-01) -> (2023-05-01)
- Regen readme and ARM templates for all modules.

## Pipeline references

| Pipeline |
| - |
| [Storage - StorageAccounts](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml) |
| [AppConfiguration - ConfigurationStores](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.appconfiguration.configurationstores.yml) |
|[Network - NetworkInterfaces](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.networkinterfaces.yml)|

# Type of Change

Please delete options that are not relevant.

- [x] Patch (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Update to documentation

# Checklist

- [ ] I'm sure there are no other open Pull Requests for the same update/change
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (readme)
- [x] I did format my code

### CODE REVIEW

**Comment by MariusStorhaug** [comment]
I have a very limited environment on my own side, so let me know which pipelines you might want me to run. If possible, might be worth pulling it in to a branch in Azure/ResourceModules and run a test from there if possible.

**Review by eriqua — CHANGES_REQUESTED** [review]
Hey @MariusStorhaug, as we're currently working on a dev branch to rename all module folders to a singular form and comply with the public Bicep registry naming, I'm putting on hold this PR until #3571 and #3572 are merged

**Comment by MariusStorhaug** [comment]
@AlexanderSehr @eriqua : I see more breakages in pipeline due to APIs growing old. Want me to include them in this PR or a separate one? A significant one is the networking RP.

**Comment by MariusStorhaug** [comment]
Merge conflict resolved by regenning the host-pools main.json file.

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr @eriqua : I see more breakages in pipeline due to APIs growing old. Want me to include them in this PR or a separate one? A significant one is the networking RP.

Though it pains me to say, I'd suggest to wait to limit conflicts with the upcoming breaking changes.

**Comment by MariusStorhaug** [comment]
> > @AlexanderSehr @eriqua : I see more breakages in pipeline due to APIs growing old. Want me to include them in this PR or a separate one? A significant one is the networking RP.
> 
> Though it pains me to say, I'd suggest to wait to limit conflicts with the upcoming breaking changes.

Any ETA for that change? :)

**Comment by AlexanderSehr** [comment]
> > > @AlexanderSehr @eriqua : I see more breakages in pipeline due to APIs growing old. Want me to include them in this PR or a separate one? A significant one is the networking RP.
> > 
> > 
> > Though it pains me to say, I'd suggest to wait to limit conflicts with the upcoming breaking changes.
> 
> Any ETA for that change? :)

Weeks ago 😬 but we're though most of it. So I'd expect within the next week or two

**Comment by eriqua** [comment]
> > > @AlexanderSehr @eriqua : I see more breakages in pipeline due to APIs growing old. Want me to include them in this PR or a separate one? A significant one is the networking RP.
> > 
> > 
> > Though it pains me to say, I'd suggest to wait to limit conflicts with the upcoming breaking changes.
> 
> Any ETA for that change? :)



> > > > @AlexanderSehr @eriqua : I see more breakages in pipeline due to APIs growing old. Want me to include them in this PR or a separate one? A significant one is the networking RP.
> > > 
> > > 
> > > Though it pains me to say, I'd suggest to wait to limit conflicts with the upcoming breaking changes.
> > 
> > 
> > Any ETA for that change? :)
> 
> Weeks ago 😬 but we're though most of it. So I'd expect within the next week or two

As soon as PR #3573 gets merged 👯

**Comment by AlexanderSehr** [comment]
> > > > @AlexanderSehr @eriqua : I see more breakages in pipeline due to APIs growing old. Want me to include them in this PR or a separate one? A significant one is the networking RP.
> > > 
> > > 
> > > Though it pains me to say, I'd suggest to wait to limit conflicts with the upcoming breaking changes.
> > 
> > 
> > Any ETA for that change? :)
> 
> > > > > @AlexanderSehr @eriqua : I see more breakages in pipeline due to APIs growing old. Want me to include them in this PR or a separate one? A significant one is the networking RP.
> > > > 
> > > > 
> > > > Though it pains me to say, I'd suggest to wait to limit conflicts with the upcoming breaking changes.
> > > 
> > > 
> > > Any ETA for that change? :)
> > 
> > 
> > Weeks ago 😬 but we're though most of it. So I'd expect within the next week or two
> 
> As soon as PR #3573 gets merged 👯

PR is merged. Now we have to fix a bunch of Api versions 😄

**Comment by MariusStorhaug** [comment]
Too many conflicts to care. Reboot PR: #3665

**Pull request closed without merging**
