### PR TITLE
Added securestring and secure() to several arm templates and biceps

### PR DESCRIPTION
**Pull request by johnlokerse**
# Description

In this PR I have added securestring and secure() to the sharedKey parameter for VPN connection to hide the value of the secret during deployments.

## Type of Change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (readme)
- [x] I did format my code

### CODE REVIEW

**Comment by AlexanderSehr** [comment]
Hey @johnlokerse, have you been successfully able to test the change on your end?

**Comment by johnlokerse** [comment]
I have ran `bicep build >bicepFilePath<` to update the main.json files, but still getting the error [Expected strings to be the same, because the [network/vpn-gateway] [main.json] should be based on the latest [main.bicep] file. Please run [ bicep build >bicepFilePath< ] using the latest Bicep CLI version.](https://github.com/johnlokerse/ResourceModules/actions/runs/6300998336). 

What ma I missing?

**Comment by AlexanderSehr** [comment]
> I have ran `bicep build >bicepFilePath<` to update the main.json files, but still getting the error on the tests: [Expected strings to be the same, because the [network/vpn-gateway] [main.json] should be based on the latest [main.bicep] file. Please run [ bicep build >bicepFilePath< ] using the latest Bicep CLI version.](https://github.com/johnlokerse/ResourceModules/actions/runs/6300998336).
> 
> @AlexanderSehr Am I missing something?

Just a tiny detail. The error is complaining about the parent `main.json` being out of date: `Expected strings to be the same, because the [network/vpn-gateway] [main.json] should be based on the latest [main.bicep] file. Please run [ bicep build >bicepFilePath< ] using the latest Bicep CLI version., but they were different.`. 
I assume you ran `bicep build` for the connection child, but that will also affect the parent. Hence you have to compile the parent (vpn-gateway) too.

**Comment by johnlokerse** [comment]
@AlexanderSehr That did the job 👍 

All tests are running green, except for the deployment validation tests because if `az login`:
* https://github.com/johnlokerse/ResourceModules/actions/runs/6303031759/job/17111528005
* https://github.com/johnlokerse/ResourceModules/actions/runs/6303030376/job/17111500322

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr That did the job 👍
> 
> All tests are running green, except for the deployment validation tests because if `az login`:
> 
> * https://github.com/johnlokerse/ResourceModules/actions/runs/6303031759/job/17111528005
> * https://github.com/johnlokerse/ResourceModules/actions/runs/6303030376/job/17111500322

Great. I take it you've been able to successfully deploy the template on your end?

**Comment by johnlokerse** [comment]
@AlexanderSehr I am on it 👍  Deployments are running as we speak, but it is taking a while

**Comment by johnlokerse** [comment]
@AlexanderSehr 

Test deployments are done:

image

✅ Hidden sharedKey from the connection deployment:

image

✅ Hidden sharedKey from the vpn-gateways deployment:

image

**Comment by AlexanderSehr** [comment]
Awesome, thank you @johnlokerse. I'll go ahead, approve and merge the PR. 
I'm sure the community will appreciate this change :)

**Review by AlexanderSehr — APPROVED** [review]

**Pull request merged**
