### PR TITLE
[Fixes] API issues

### LINKED ISSUE #3538: [Failed pipeline] Purview - Accounts
failed run: https://github.com/Azure/ResourceModules/actions/runs/5774871029

### LINKED ISSUE #3600: [Failed pipeline] Network - BastionHosts
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332072

### LINKED ISSUE #3601: [Failed pipeline] DataFactory - Factories
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332164

### LINKED ISSUE #3602: [Failed pipeline] AppConfiguration - ConfigurationStores
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332172

### LINKED ISSUE #3603: [Failed pipeline] Network - PrivateEndpoints
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332126

### LINKED ISSUE #3605: [Failed pipeline] EventGrid - Topics
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332160

### LINKED ISSUE #3606: [Failed pipeline] Network - VirtualNetworks
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332097

### LINKED ISSUE #3607: [Failed pipeline] ContainerRegistry - Registries
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332184

### LINKED ISSUE #3608: [Failed pipeline] Insights - PrivateLinkScopes
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332268

### LINKED ISSUE #3609: [Failed pipeline] Network - LocalNetworkGateways
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332086

### LINKED ISSUE #3610: [Failed pipeline] Batch - BatchAccounts
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332207

### LINKED ISSUE #3611: [Failed pipeline] Synapse - Workspaces
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332158

### LINKED ISSUE #3613: [Failed pipeline] Network - AzureFirewalls
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332181

### LINKED ISSUE #3614: [Failed pipeline] RecoveryServices - Vaults
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332193

### LINKED ISSUE #3615: [Failed pipeline] Network - NetworkWatchers
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332049

### LINKED ISSUE #3616: [Failed pipeline] Network - PublicIpPrefixes
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332163

### LINKED ISSUE #3617: [Failed pipeline] Network - NatGateways
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332118

### LINKED ISSUE #3618: [Failed pipeline] EventGrid - Domains
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332224

### LINKED ISSUE #3619: [Failed pipeline] DocumentDB - DatabaseAccounts
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332087

### LINKED ISSUE #3620: [Failed pipeline] Network - IpGroups
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332121

### LINKED ISSUE #3621: [Failed pipeline] Network - VPNGateways
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332089

### LINKED ISSUE #3622: [Failed pipeline] Automation - AutomationAccounts
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332169

### LINKED ISSUE #3624: [Failed pipeline] Network - LoadBalancers
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332111

### LINKED ISSUE #3625: [Failed pipeline] Network - NetworkSecurityGroups
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332147

### LINKED ISSUE #3627: [Failed pipeline] Network - RouteTables
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332248

### LINKED ISSUE #3628: [Failed pipeline] Network - FirewallPolicies
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332078

### LINKED ISSUE #3629: [Failed pipeline] Network - ApplicationSecurityGroups
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332148

### LINKED ISSUE #3631: [Failed pipeline] Network - NetworkInterfaces
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332192

### LINKED ISSUE #3632: [Failed pipeline] Network - VirtualWans
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332183

### LINKED ISSUE #3635: [Failed pipeline] Sql - Servers
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332134

### LINKED ISSUE #3637: [Failed pipeline] Compute - VirtualMachines
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332177

### LINKED ISSUE #3638: [Failed pipeline] Web - StaticSites
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332189

### LINKED ISSUE #3640: [Failed pipeline] DigitalTwins - DigitalTwinsInstances
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332185

### LINKED ISSUE #3641: [Failed pipeline] Network - PublicIpAddresses
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332128

### LINKED ISSUE #3642: [Failed pipeline] Web - Sites
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332069

### LINKED ISSUE #3644: [Failed pipeline] SignalRService - SignalR
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332092

### LINKED ISSUE #3645: [Failed pipeline] Network - ApplicationGateways
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332125

### LINKED ISSUE #3646: [Failed pipeline] Network - ServiceEndpointPolicies
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332099

### LINKED ISSUE #3647: [Failed pipeline] MachineLearningServices - Workspaces
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332188

### LINKED ISSUE #3648: [Failed pipeline] SignalRService - WebPubSub
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332205

### LINKED ISSUE #3649: [Failed pipeline] KeyVault - Vaults
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332222

### LINKED ISSUE #3650: [Failed pipeline] Network - ExpressRouteCircuits
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332081

### LINKED ISSUE #3651: [Failed pipeline] ServiceBus - Namespaces
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332139

### LINKED ISSUE #3653: [Failed pipeline] Synapse - PrivateLinkHubs
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332243

### LINKED ISSUE #3654: [Failed pipeline] CognitiveServices - Accounts
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332251

### LINKED ISSUE #3656: [Failed pipeline] Storage - StorageAccounts
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332137

### LINKED ISSUE #3658: [Failed pipeline] Network - VPN Sites
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332173

### LINKED ISSUE #3659: [Failed pipeline] Network - Connections
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332179

### LINKED ISSUE #3660: [Failed pipeline] Cache - Redis
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332162

### LINKED ISSUE #3661: [Failed pipeline] Network - DdosProtectionPlans
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332250

### LINKED ISSUE #3662: [Failed pipeline] Relay - Namespaces
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332144

### LINKED ISSUE #3663: [Failed pipeline] EventHub - Namespaces
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332074

### LINKED ISSUE #3664: [Failed pipeline] Network - VirtualNetworkGateways
failed run: https://github.com/Azure/ResourceModules/actions/runs/5924332143

### PR DESCRIPTION
**Pull request by MariusStorhaug**
## ℹ️ Info ℹ️

- The pipelines have been run without deployments due to limits in my own environment.
- Updates network APIs to 2023-04-01.

Some out of scope changes:

- Update the networkWatcher test deployment name, where it was using the wrong location to set name. Very small and insignificant.

## Description

<details>
<summary>Issues that this PR fixes</summary>

Closes #3600
Closes #3601
Closes #3602
Closes #3603
Closes #3605
Closes #3606
Closes #3607
Closes #3608
Closes #3609
Closes #3610
Closes #3611
Closes #3613
Closes #3614
Closes #3615
Closes #3616
Closes #3617
Closes #3618
Closes #3619
Closes #3620
Closes #3621
Closes #3622
Closes #3624
Closes #3625
Closes #3627
Closes #3628
Closes #3629
Closes #3631
Closes #3632
Closes #3635
Closes #3637
Closes #3638
Closes #3640
Closes #3641
Closes #3642
Closes #3644
Closes #3645
Closes #3646
Closes #3647
Closes #3648
Closes #3649
Closes #3650
Closes #3651
Closes #3653
Closes #3654
Closes #3656
Closes #3658
Closes #3659
Closes #3660
Closes #3661
Closes #3662
Closes #3663
Closes #3664
Closes #3538 - Last pipeline failed due to outdated API, though there is more regarding location issues in previous logs.

</details>

Changes:

- [x] Regen readme and ARM templates for all modules.
- [x] API version bump of modules. (badges are from my main branch, no validation deployments)
  - [x} applicationGateways (2022-07-01) -> (2023-04-01) | [Network - ApplicationGateways](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.applicationgateways.yml)
  - [x] applicationSecurityGroups (2022-07-01) -> (2023-04-01) [Network - ApplicationSecurityGroups](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.applicationsecuritygroups.yml)
  - [x] azureFirewalls (2022-07-01) -> (2023-04-01) [Network - AzureFirewalls](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.azurefirewalls.yml)
  - [x] connections (2022-07-01) -> (2023-04-01) [Network - Connections](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.connections.yml)
  - [x] ddosProtectionPlans (2022-07-01) -> (2023-04-01) [Network - DdosProtectionPlans](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.ddosprotectionplans.yml)
  - [x] expressRouteCircuits (2022-07-01) -> (2023-04-01) [Network - ExpressRouteCircuits](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.expressroutecircuits.yml)
  - [x] expressRouteGateways (2022-07-01) -> (2023-04-01) [Network - ExpressRouteGateways](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.expressroutegateways.yml)
  - [x] firewallPolicies (2022-07-01) -> (2023-04-01) [Network - FirewallPolicies](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.firewallpolicies.yml)
  - [x] ipGroups (2022-07-01) -> (2023-04-01) [Network - IpGroups](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.ipgroups.yml)
  - [x] loadBalancers (2022-07-01) -> (2023-04-01) [Network - LoadBalancers](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.loadbalancers.yml)
  - [x] localNetworkGateways (2022-07-01) -> (2023-04-01) [Network - LocalNetworkGateways](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.localnetworkgateways.yml)
  - [x] natGateways (2022-07-01) -> (2023-04-01) [Network - NatGateways](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.natgateways.yml)
  - [x] networkInterfaces (2021-08-01, 2022-05-01, 2022-07-01) -> (2023-04-01)
    - New parameter: `auxilarySku`
    - compute/virtual-machine [Compute - VirtualMachines](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml)
    - network/network-interface [Network - NetworkInterfaces](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.networkinterfaces.yml)
    - tests updated that were deploying `networkInterfaces`
      - network/network-watcher
  - [x] networkSecurityGroups (2022-07-01) -> (2023-04-01) [Network - NetworkSecurityGroups](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.networksecuritygroups.yml)
    - tests updated that were deploying `networkSecurityGroups`
      - network/network-watcher
      - network/virtual-network
      - sql/managed-instance
      - synapse/private-link-hub
      - web/hosting-environment
  - [x] networkWatchers (2022-07-01) -> (2023-04-01) [Network - NetworkWatchers](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.networkwatchers.yml)
    - networkWatchers/connectionMonitors (2022-07-01) -> (2023-04-01)
    - networkWatchers/flowLogs (2022-07-01) -> (2023-04-01)
  - [x] privateEndpoints (2022-07-01) -> (2023-04-01) [Network - PrivateEndpoints](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.privateendpoints.yml)
    - privateEndpoints/privateDnsZoneGroups (2022-07-01) -> (2023-04-01)
    - dependencies updated for:
      - app-configuration/configuration-store
      - automation/automation-account
      - batch/batch-account
      - cache/redis
      - cognitive-services/account
      - container-registry/registry
      - data-factory/factory
      - digital-twins/digital-twins-instance
      - document-db/database-account
      - event-grid/domain
      - event-grid/topic
      - event-hub/namespace
      - insights/private-link-scope
      - key-vault/vault
      - machine-learning-services/workspace
      - purview/account
      - recovery-services/vault
      - relay/namespace
      - service-bus/namespace
      - signal-r-service/signal-r
      - signal-r-service/web-pub-sub
      - sql/server
      - storage/storage-account
      - synapse/private-link-hub
      - synapse/workspace
      - web/site
      - web/site/slot
      - web/static-site
  - [x] publicIPAddresses (2022-07-01) -> (2023-04-01) [Network - PublicIpAddresses](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.publicipaddresses.yml)
    - New parameter: `domainNameLabelScope`
    - dependencies updated for:
      - compute/virtual-machine
      - network/azure-firewall
      - network/bastion-host
      - network/nat-gateway
      - network/virtual-network-gateway
    - tests updated that were deploying `publicIPAddresses`
      - network/application-gateway
      - network/azure-firewall
      - network/bastion-host
      - network/connection
      - network/load-balancer
  - [x] publicIPPrefixes (2022-07-01) -> (2023-04-01) [Network - PublicIpPrefixes](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.publicipprefixes.yml)
  - [x] routeTables (2022-07-01) -> (2023-04-01) [Network - RouteTables](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.routetables.yml)
    - tests updated that were deploying `routeTables`
      - virtual-network
      - sql/managed-instance
  - [x] serviceEndpointPolicies (2022-07-01) -> (2023-04-01) [Network - ServiceEndpointPolicies](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.serviceendpointpolicies.yml)
  - [x] virtualNetworkGateways  (2022-07-01) -> (2023-04-01) [Network - VirtualNetworkGateways](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.virtualnetworkgateways.yml)
    - tests updated that were deploying `virtualNetworkGateways`
      - modules/network/connection
  - [x] virtualNetworks (2022-07-01) -> (2023-04-01) [Network - VirtualNetworks](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml)
    - tests updated that were deploying `virtualNetworks`
      - aad/domain-service
      - app-configuration/configuration-store
      - app/managed-environment
      - automation/automation-account
      - batch/batch-account
      - cache/redis
      - cognitive-services/account
      - compute/virtual-machine-scale-set
      - compute/virtual-machine
      - container-instance/container-group
      - container-registry/registry
      - container-service/managed-cluster
      - data-factory/factory
      - db-for-my-sql/flexible-server
      - db-for-postgre-sql/flexible-server
      - dev-test-lab/lab
      - digital-twins/digital-twins-instance
      - document-db/database-account
      - event-grid/domain
      - event-grid/topic
      - event-hub/namespace
      - insights/private-link-scope
      - key-vault/vault
      - machine-learning-services/workspace
      - net-app/net-app-account
      - network/application-gateway
      - network/azure-firewall
      - network/bastion-host
      - network/connection
      - network/dns-forwarding-ruleset
      - network/dns-resolver
      - network/load-balancer
      - network/network-interface
      - network/network-manager
      - network/network-watcher
      - network/private-dns-zone
      - network/private-endpoint
      - network/private-link-service
      - network/virtual-hub
      - network/virtual-network-gateway
      - purview/account
      - recovery-services/vault
      - relay/namespace
      - relay/namespace
      - service-bus/namespace
      - signal-r-service/signal-r
      - signal-r-service/web-pub-sub
      - sql/managed-instance
      - sql/server
      - storage/storage-account
      - synapse/private-link-hub
      - synapse/workspace
      - virtual-machine-images/image-template
      - web/hosting-environment
      - web/site
      - web/static-site
  - [x] virtualWans (2022-07-01) -> (2023-04-01) [Network - VirtualWans](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.virtualwans.yml)
    - tests updated that were deploying `routeTables`
      - network/azure-firewall
      - network/express-route-gateway
      - network/virtual-hub
      - network/vpn-gateway
      - network/vpn-site
  - [x] vpnGateways (2022-07-01) -> (2023-04-01) [Network - VPNGateways](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.vpngateways.yml)
  - [x] vpnSites (2022-07-01) -> (2023-04-01) [Network - VPN Sites](https://github.com/MariusStorhaug/ResourceModules/actions/workflows/ms.network.vpnsites.yml)
    - tests updated that were deploying `vpnSites`
      - network/vpn-gateway

# Type of Change

- [x] Patch (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Update to documentation

# Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (readme)
- [x] I did format my code

### CODE REVIEW

**Comment by ahmadabdalla** [comment]
@MariusStorhaug I'd recommend we use a documented API version (i.e. `2023-04-01` in the case of networking) as if we introduce new parameters that are not documented publicly that may cause confusion. 

On a side note @AlexanderSehr @eriqua do we know someone who can update the public documentation to show the latest API that Marius has used in this PR ==> `2023-05-01`

**Comment by MariusStorhaug** [comment]
Before I change this, is there a consensus that the docs needs to be available? I don't see this described in the guide. If this is the decision of the team, please PR that in to the docs.

**Comment by eriqua** [comment]
> @ahmadabdalla Before I change this, is there a consensus that the docs needs to be available? I don't see this described in the guide. If this is the decision of the team, please PR that in to the docs.

There's no strict rule, but I'd agree with @ahmadabdalla point on using the latest documented API.

**Comment by MariusStorhaug** [comment]
Will regen it with 2023.04.01. Bear with me...

**Comment by AlexanderSehr** [comment]
@MariusStorhaug #3576 is now in main :)

**Comment by MariusStorhaug** [comment]
Merged a branch of this into my main to trigger all tests, no validation deployments however. Pipeline status badges in description are now showing my main branch (this content + disabling validation deployments). https://github.com/MariusStorhaug/ResourceModules/pull/4

**Comment by ahmadabdalla** [comment]
@MariusStorhaug I did a quick test for one of the resources `network security groups` and the pipeline failed. See here please https://github.com/Azure/ResourceModules/actions/runs/5986909916/job/16240582399

```powershell
  VERBOSE: 20:56:07 - The deployment 'n-nsg-common-t1-20230826T2008187382Z' failed with error(s). Showing 2 out of 2 error(s).
  Status Message: Diagnostic settings does not support retention for new diagnostic settings. (Code:BadRequest)
  
  Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details. (Code: DeploymentFailed)
   - {
    "code": "BadRequest",
    "message": "Diagnostic settings does not support retention for new diagnostic settings."
  } (Code:BadRequest)
  ```

I've seen this error pop up recently on a customer environment, and saw this issue on TF relating to something similar:
https://github.com/hashicorp/terraform-provider-azurerm/issues/23051

On a doc, I found that the `retention settings` is being deprecated https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/migrate-to-azure-storage-lifecycle-policy

https://github.com/MicrosoftDocs/azure-docs/issues/113490

We have an issue opened on this topic https://github.com/Azure/ResourceModules/issues/3572 with a PR from @AlexanderSehr https://github.com/Azure/ResourceModules/pull/3721 that is still in draft.

Merging this PR will not result in successful pipelines for the Network resources and all other modules that use the diagnostics retention settings. Merging PR #3721 will fix diagnostics but fail network pipelines but at least succeed for resources that don't rely on private endpoints dependency. A chicken and egg situation. 

CC @eriqua

**Comment by MariusStorhaug** [comment]
@ahmadabdalla @eriqua @AlexanderSehr : How about we merge it into a dev branch in Azure/ResourceModules, and use that to get all things working?

**Comment by AlexanderSehr** [comment]
> @ahmadabdalla @eriqua @AlexanderSehr : How about we merge it into a dev branch in Azure/ResourceModules, and use that to get all things working?

We could do that. It would however, become a very massive Pull Request. I believe it is about 60 modules that I updated in the other PR, and the only reason it remained in draft was that I'm still not sure if I understood / resolved the issue correctly. As @eriqua will be out for another week, would you @ahmadabdalla be able to take a look from your end? 
I think this PR is good as it is, so I'd suggest to review the Diagnostic PR #3721 first, separately, before merging the two together in one branch and run all pipelines.

**Comment by ahmadabdalla** [comment]
@AlexanderSehr will review it tonight 🚀

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr will review it tonight 🚀

Alright, great. I went ahead and created the branch `users/alsehr/devApiAndDiag`. I'll redirect @MariusStorhaug PR to this branch and close this PR. Once the other one is reviewed we can merge it there too and run a full end-to-end test.

**Pull request merged**
