### PR TITLE
[Modules] Updated VNET Gateway to reference PIP module

### PR DESCRIPTION
**Pull request by lsnoddy**
# Description

Refactored the virtualNetworkGateways module to reference the publicIPAddresses module instead of implementing a resource:
- Removed virtualGatewayPublicIP_lock resource since managed by PIP module
- Removed virtualNetworkGatewayPublicIp_diagnosticSettings since managed by PIP module
- Removed publicIpDiagnosticsLogsSpecified and publicIpDiagnosticsLogs variables as no longer required

Added dnsSettings property to publicIPAddresses module since VNET gateway used one of the parameters (domainNameLabel)
- Added optional parameters domainNameLabel, fqdn, reverseFqdn
- Added dnsSettings in properties

| Pipeline |
| - |
| |
[Network: VirtualNetworkGateways](https://github.com/lsnoddy/ResourceModules/actions/workflows/ms.network.virtualnetworkgateways.yml)
[Network: PublicIpAddresses](https://github.com/lsnoddy/ResourceModules/actions/workflows/ms.network.publicipaddresses.yml)

# Type of Change

Please delete options that are not relevant.

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Update to documentation

# Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (readme)
- [x] I did format my code

### CODE REVIEW

**Comment by ahmadabdalla** [comment]
@lsnoddy .. shouldn't the gateway documentation now include the public IP address module in the [Cross-referenced modules](https://github.com/Azure/ResourceModules/tree/main/modules/Microsoft.Network/virtualNetworkGateways#cross-referenced-modules) section? 

Example from another module: 
https://github.com/Azure/ResourceModules/tree/main/modules/Microsoft.ContainerRegistry/registries#cross-referenced-modules

**Review by AlexanderSehr — APPROVED** [review]

**Comment by AlexanderSehr** [comment]
> @lsnoddy .. shouldn't the gateway documentation now include the public IP address module in the [Cross-referenced modules](https://github.com/Azure/ResourceModules/tree/main/modules/Microsoft.Network/virtualNetworkGateways#cross-referenced-modules) section?
> 
> Example from another module: https://github.com/Azure/ResourceModules/tree/main/modules/Microsoft.ContainerRegistry/registries#cross-referenced-modules

Actually true. @lsnoddy, please run the ReadMe generation for that module too.

**Review by AlexanderSehr — CHANGES_REQUESTED** [review]
See other comments: Readme Generation for VNET GW module wasn't run yet.

**Comment by lsnoddy** [comment]
Thanks for catching @ahmadabdalla  and @AlexanderSehr . Ran the readme update script for VNET gateway.

**Review by AlexanderSehr — APPROVED** [review]

**Pull request merged**
