### PR TITLE
#435 remove child resources first

### PR DESCRIPTION
**Pull request by simonbMS**
# Change
Removes child resources before removing parent, when child resource is returned by get-azresource. Assumes child resource is in the same resource group

Fixes [this bug](https://github.com/Azure/ResourceModules/issues/435) for Image Gallery, not experienced yet in other resources

Tested with 
- Storage account: https://github.com/Azure/ResourceModules/actions/runs/1434845284
- Load balancer: https://github.com/Azure/ResourceModules/actions/runs/1434802445
- Image gallery: https://github.com/Azure/ResourceModules/actions/runs/1434761374

## Type of Change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (Wiki)

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (readme)
- [x] I did format my code

### CODE REVIEW

**Review by eriqua — CHANGES_REQUESTED** [review]
I'd suggest to move this PR to Draft and align on how to integrate it into the bigger picture (ref issue #431 and other removal related)

**Comment by MrMCake** [comment]
@simonbMS I agree with @eriqua's comment. We should definitely build this logic into the other PR (ideally once merged). I'd suggest to leverage a recursive function and essentially use it to find all children, put all in a flat list (ordered by child-resource-depth) and then hand it over to the removal fuction to remove all resources from the childest-child to the top resource.

**Comment by MrMCake** [comment]
Linking to branch : `users/alsehr/simonebMSRemoval`

**Comment by MrMCake** [comment]
@simonbMS I guess we can remove this PR

**Comment by simonbMS** [comment]
Closing this one as replaced by https://github.com/Azure/ResourceModules/pull/471

**Pull request closed without merging**
