### PR TITLE
[Modules] Microsoft.Compute/VirtualMachines - New Feature AADLogin extension

### PR DESCRIPTION
**Pull request by shawntmeyer**
# Description

Added new parameter, test cases and logic to support configuration of the AADLogin extension for Windows and Linux.

| Pipeline |
| - |
| [Compute: VirtualMachines](https://github.com/shawntmeyer/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml) |

# Type of Change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] Update to documentation

# Checklist

- [X] I'm sure there are no other open Pull Requests for the same update/change
- [X] My corresponding pipelines / checks run clean and green without any errors or warnings
- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (readme)
- [X] I did format my code

### CODE REVIEW

**Review by shawntmeyer — COMMENTED** [review]
resync and resubmit of PR

**Comment by ChrisSidebotham** [comment]
@shawntmeyer  -  Are you able to provide a status badge from deployment test?

**Comment by shawntmeyer** [comment]
Im not sure how to do that, im sorry.

Sent via the Samsung Galaxy S22 Ultra 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AlexanderSehr** [comment]
> Im not sure how to do that, im sorry

Hey @shawntmeyer, just added one for you. You can create a status badge by 
- navigating to your actions, then the VM pipeline
- then click on the three `...` on the top right (which opens a dropdown)
- select 'Create Status Badge'
- select your branch in the popup 
- and finally just copy the markdown text

[Compute: VirtualMachines](https://github.com/shawntmeyer/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml)

Anyhow, the badge currently shows that the pipeline did not run. Any chance you could run the VM pipeline with this branch in your test subscription?

**Comment by shawntmeyer** [comment]
Now that I have my GitHub Actions workflow setup I'm unable to get a successful test of the Virtual Machines module from my Main Branch or this feature branch. The main branch is a direct fork and sync with the Azure\ResourceModules repository. Here is the message I receive in the workflow output:

In [Microsoft.Compute/virtualMachines] used resource type [vaults/backupFabrics/protectionContainers/protectedItems] should use one of the recent API version(s). Currently using [2022-02-01] 27ms (26ms|1ms)

**Comment by shawntmeyer** [comment]
closing to resync my main fork

**Pull request closed without merging**
