### PR TITLE
[Modules] Support for in Guest Patch support with Azure Update Manager

### PR DESCRIPTION
**Pull request by jdrepo**
# Description

Based on #3954 

</details>

Support for the "installPatches" property in the Microsoft.Maintenance/maintenanceConfigurations resource

### Pipeline references

| Pipeline |
| - |
|[Maintenance - MaintenanceConfigurations](https://github.com/jdrepo/ResourceModules/actions/workflows/ms.maintenance.maintenanceconfigurations.yml) |

## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (readme)
- [ ] I did format my code

### CODE REVIEW

**Comment by AlexanderSehr** [comment]
Hey @jdrepo, the PR actually looked very good 😄 Anything we can help with?

**Comment by jdrepo** [comment]
@microsoft-github-policy-service agree


Am Di., 12. Sept. 2023 um 12:29 Uhr schrieb
microsoft-github-policy-service[bot] ***@***.***>:

**Comment by AlexanderSehr** [comment]
Hey @jdrepo, no you did everything correctly. Git just includes all your changes from main, no matter what (which includes the settings.yml). What we recommend is to implement your change, open a release/merge/temp branch in which you undo the settings.yml changes and the open a PR from that one. This way, your main branch remains the same (with your settings) and only the desired changes are part of the PR.

**Comment by AlexanderSehr** [comment]
There aren't many other ways and it's just the nature of git we have to work around. 🤔

**Comment by jdrepo** [comment]
Hello @AlexanderSehr,
thanks for bringing me on the right track  

In the meantime I created another branch and now there a some more changes included ( README.md / docs/wiki/The library - Module overview.md / modules/maintenance/maintenance-configuration/README.md )

What will happen to the PR if I leave the settings.yml and other files included, will you sort it out, when you merge the PR to your main branch ?

**Comment by AlexanderSehr** [comment]
There are workarounds that would lows this, but generally no. We have our own settings.yml you'd overwrite for our CI environment 😂

My proposal are the flowing steps
- Open a PR from your branch
- Check in the PR what files are included and if there are any undesired ones (like the settings.yml & docs)
- In a separate tab, navigate to the target branch (that is our repository's main branch) and get and overwrite any undesired changes in your branch with the version we have in our repository

Doing so will effectively remove the changes from the PR, as your version would be 1:1 what is in our Repo (aka no changes).

**Comment by jdrepo** [comment]
Hi @AlexanderSehr , thanks for your input and hints for a GitHub newbie :-)
In the meantime I created another PR, hopefully with the right files in it.

**Pull request closed without merging**
